import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import handlebars from 'handlebars/dist/cjs/handlebars'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [template, setTemplate] = useState('');

  const [introText, setIntroText] = useState('hey every one this is {{brandData.brandName}}. Our description is {{brandData.productDescription}}. We are giving you {{brandData.rewardsCPC}}% cashback on your first purchase. Hurry up and shop now.');

  const [buttonColor, setButtonColor] = useState('');
  const [textColor, setTextColor] = useState('');
  const [bgColor, setBgColor] = useState('');
  const [LINKCOLOR, setLINKCOLOR] = useState('');

  const [showAvailableData, setShowAvailableData] = useState(false);

  let brandData = {
    "brandName": "Nutr",
    "firstName": "Mohit",
    "image1": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667756/common/Group_1000002675_aigpqs.png",
    "image2": "https://brand-templates-data-prod.s3.us-east-2.amazonaws.com/Nutr/NutrImage2.png",
    "image3": "https://brand-templates-data-prod.s3.us-east-2.amazonaws.com/Nutr/NutrImage3.png",
    "brandLogo": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667625/common/Nutr_x_youshd_sx079u.png",
    "combinedLogo": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667625/common/Nutr_x_youshd_sx079u.png",
    "shopUrl": "https://thenutr.com/",
    "productDescription": "Best product of the world",
    "rewardsCPC": 1,
    "rewardsCPC100": 100,
    "rewardsMaximum": 1000,
    "instagramHandle": "realnutr",
    "tiktokHandle": "tiktoknutr",
    "instagram": true,
    "bgColor": "wheat",
    "textColor": "maroon",
    "buttonColor": "maroon",
    "LINKCOLOR": "blue",
    // editable text
    "introText": "This is default text",
  }

  useEffect(() => {
    const getTemplate = async () => {
      const res = await fetch('/api/get-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(
          {
            "brandName": "Nutr",
            "firstName": "Mohit",
            "image1": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667756/common/Group_1000002675_aigpqs.png",
            "image2": "https://brand-templates-data-prod.s3.us-east-2.amazonaws.com/Nutr/NutrImage2.png",
            "image3": "https://brand-templates-data-prod.s3.us-east-2.amazonaws.com/Nutr/NutrImage3.png",
            "brandLogo": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667625/common/Nutr_x_youshd_sx079u.png",
            "combinedLogo": "https://res.cloudinary.com/dqsbiaqqj/image/upload/v1677667625/common/Nutr_x_youshd_sx079u.png",
            "shopUrl": "https://thenutr.com/",
            "productDescription": "Best product of the world",
            "rewardsCPC": 1,
            "rewardsCPC100": 100,
            "rewardsMaximum": 1000,
            "instagramHandle": "realnutr",
            "tiktokHandle": "tiktoknutr",
            "instagram": true,
            "bgColor": "wheat",
            "textColor": "maroon",
            "buttonColor": "maroon",
            "LINKCOLOR": "blue",
            // editable text
            "introText": "This is default text",
          }
        ),
      })

      const data = await res.json();


      let bare = data.bareTemplate;

      // // compile the template with handlebars
      // const bareTemplate = handlebars.compile(bare)
      // console.log(bareTemplate({
      //   ...brandData
      // }))

      // data.template = data.template.replace("This is default text", `${introText}`)
      setTemplate(data.bareTemplate);
      setButtonColor(brandData.buttonColor);
      setTextColor(brandData.textColor);
      setBgColor(brandData.bgColor);
      setLINKCOLOR(brandData.LINKCOLOR);


    }


    getTemplate()
  }, []);


  // write a function to use the above brandData as {{brandData.brandName}} in the template
  const SimpleHandleBarParser = (template) => {
    let parsedTemplate = template;
    for (let key in brandData) {
      parsedTemplate = parsedTemplate.replace(`{{brandData.${key}}}`, brandData[key]);
    }
    return parsedTemplate;
  }

  function renderTemplate() {
    return { __html: handlebars.compile(template)(
      {
        ...brandData,
        // compile introText with handlebars
        introText: SimpleHandleBarParser(introText),
        buttonColor: buttonColor,
        textColor: textColor,
        bgColor: bgColor,
        LINKCOLOR: LINKCOLOR,
      }
    ) };
  }

  
  
  useEffect(() => {
    
  },[introText])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection: 'column',
            padding: '1rem',
          }}
        >
          <h1 className={styles.title}>
            Sasta Email Template Editor
          </h1>
          <p style={{
            textAlign: 'center',
          }}>
            Get started by editing
          </p>
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <div>
            <h1>Template</h1>
            <hr/>
            <h4>
              Introduction text
            </h4>
            <hr/>
            <h4
            id="available-data"
            onMouseEnter={() => {
              setShowAvailableData(true)
            }}
            onMouseLeave={() => {
              setShowAvailableData(false)
            }}
>Available Data to use</h4>
            {
              showAvailableData && (
                <div
                style={{
                  padding: '1rem',
                  backgroundColor: 'lightgray',
                  borderRadius: '1rem',
                  position: 'absolute',
                  top: '100px',
                  left: '0',
                  zIndex: '100',
                }}
                >
                  <pre>
                    {JSON.stringify(brandData, null, 2)}
                  </pre>
                </div>
              )
            }
            <textarea
            value={introText}
            onChange={(e) => {
              console.log(e.target.value)
              setIntroText(e.target.value)
            }}
            style={{
              width: '400px',
              height: '100px',
              padding: '1rem',
              fontSize: '1rem',
            }}
            >
            </textarea>
            <h4>Button Color</h4>
            <input
              type="color"
              value={buttonColor}
              onChange={(e) => {
                setButtonColor(e.target.value)
              }}
            />
            <h4>Text Color</h4>
            <input
              type="color"
              value={textColor}
              onChange={(e) => {
                setTextColor(e.target.value)
              }}
            />
            <h4>Background Color</h4>
            <input
              type="color"
              value={bgColor}
              onChange={(e) => {
                setBgColor(e.target.value)
              }}
            />
            <h4>Link Color</h4>
            <input
              type="color"
              value={LINKCOLOR}
              onChange={(e) => {
                setLINKCOLOR(e.target.value)
              }}
            />

          </div>
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <div dangerouslySetInnerHTML={
              renderTemplate()
            } />
          </div>
          <Link href="/thankyou">
            thhankyou
          </Link>
        </div>

      </main>
    </>
  )
}
